server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/finance_vault
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Ov23liJOIRogAezttM9v
#            client-secret: 237744e5e35dca2ce94881955a1ef22f2cc57d14